#!/bin/sh

alias j='just'
alias f='zi'
alias g='lazygit'
alias v='nvim'
alias nvimrc='nvim ~/.config/nvim/'
alias ...="cd ../.."
alias ....="cd ../../.."

alias ls="eza"
alias la="ls -la"
alias tree="eza --tree --level=2"
