#!/bin/sh

lvenv() {
    venv_regex='\./\.?\(venv\|env\)'
    venv_folder=$(find './' -maxdepth 1 -type d -regex "$venv_regex" | head -n 1)

	venv_activation_script="${venv_folder}/bin/activate"

    if [ ! -f "$venv_activation_script" ]; then
        echo "file $venv_activation_script does not exist"
        return 1
    fi

	if [ -x "$venv_activation_script" ]; then
        . "$venv_activation_script"
    else
        echo "file $venv_activation_script is not executable" 
        return 1
    fi

    return 0;
}
